//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string CityState { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PhoneDescription { get; set; }
        public string Email { get; set; }
        public string EMailDescription { get; set; }
    }
}
