//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string Header { get; set; }
        public Nullable<int> Row { get; set; }
        public string Image { get; set; }
        public string Detail { get; set; }
        public string Link { get; set; }
        public Nullable<int> LinkType { get; set; }
    }
}
